{
  "type": "record",
  "namespace": "com.pulserank.schema.event",
  "name": "ProductEvent",
  "fields": [
    {
      "name": "eventId",
      "type": "string"
    },
    {
      "name": "userId",
      "type": "string"
    },
    {
      "name": "productId",
      "type": "string"
    },
    {
      "name": "eventType",
      "type": {
        "type": "enum",
        "name": "EventType",
        "symbols": [
          "VIEW",
          "CLICK",
          "WISHLIST",
          "CART",
          "PURCHASE"
        ]
      }
    },
    {
      "name": "eventTime",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "schemaVersion",
      "type": "int",
      "default": 1
    }
  ]
}