name: pulserank
services:
  postgres:
    image: postgres:17.6
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - pulserank

  kafka-init:
    image: alpine:3.22
    user: root
    command: >
      sh -c "
        mkdir -p /tmp/kraft-combined-logs &&
        chown -R 1000:1000 /tmp/kraft-combined-logs
      "
    volumes:
      - kafka-data:/tmp/kraft-combined-logs
    networks:
      - pulserank

  kafka:
    image: apache/kafka:4.1.0
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,DOCKER://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,DOCKER://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    networks:
      - pulserank

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: PulseRank
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    networks:
      - pulserank

  clickhouse:
    image: clickhouse/clickhouse-server:25.6
    ports:
      - "8123:8123"   # HTTP
      - "9000:9000"   # Native protocol
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test:
        [
          "CMD",
          "clickhouse-client",
          "--query",
          "SELECT 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - pulserank

  jobmanager:
    image: flink:2.1.0-java21
    command: jobmanager
    ports:
      - "8081:8081"
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
    networks:
      - pulserank

  taskmanager:
    image: flink:2.1.0-java21
    command: taskmanager
    depends_on:
      - jobmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
    networks:
      - pulserank

  apicurio:
    image: apicurio/apicurio-registry:3.2.6
    ports:
      - "8084:8080"
    networks:
      - pulserank

networks:
  pulserank:
    name: pulserank

volumes:
  postgres-data:
  kafka-data:
  clickhouse-data:
  grafana-data: