spring:
  application:
    name: event-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.apicurio.registry.serde.avro.AvroKafkaSerializer
    properties:
      apicurio.registry.url: http://localhost:8084/apis/registry/v3
      apicurio.registry.auto-register: true

server:
  port: 8082